!function(c){c(function(){var a=c.support,e;a:{e=document.createElement("bootstrap");var b={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},d;for(d in b)if(void 0!==e.style[d]){e=b[d];break a}e=void 0}a.transition=e&&{end:e}})}(window.jQuery);
!function(c){var a=function(a){c(a).on("click",'[data-dismiss="alert"]',this.close)};a.prototype.close=function(a){function b(){g.trigger("closed").remove()}var d=c(this),f=d.attr("data-target"),g;f||(f=(f=d.attr("href"))&&f.replace(/.*(?=#[^\s]*$)/,""));g=c(f);a&&a.preventDefault();g.length||(g=d.hasClass("alert")?d:d.parent());g.trigger(a=c.Event("close"));a.isDefaultPrevented()||(g.removeClass("in"),c.support.transition&&g.hasClass("fade")?g.on(c.support.transition.end,b):b())};c.fn.alert=function(e){return this.each(function(){var b=
c(this),d=b.data("alert");d||b.data("alert",d=new a(this));"string"==typeof e&&d[e].call(b)})};c.fn.alert.Constructor=a;c(document).on("click.alert.data-api",'[data-dismiss="alert"]',a.prototype.close)}(window.jQuery);
!function(c){var a=function(a,b){this.$element=c(a);this.options=c.extend({},c.fn.button.defaults,b)};a.prototype.setState=function(a){var b=this.$element,d=b.data(),c=b.is("input")?"val":"html";a+="Text";d.resetText||b.data("resetText",b[c]());b[c](d[a]||this.options[a]);setTimeout(function(){"loadingText"==a?b.addClass("disabled").attr("disabled","disabled"):b.removeClass("disabled").removeAttr("disabled")},0)};a.prototype.toggle=function(){var a=this.$element.closest('[data-toggle="buttons-radio"]');
a&&a.find(".active").removeClass("active");this.$element.toggleClass("active")};c.fn.button=function(e){return this.each(function(){var b=c(this),d=b.data("button"),f="object"==typeof e&&e;d||b.data("button",d=new a(this,f));"toggle"==e?d.toggle():e&&d.setState(e)})};c.fn.button.defaults={loadingText:"loading..."};c.fn.button.Constructor=a;c(document).on("click.button.data-api","[data-toggle^=button]",function(a){a=c(a.target);a.hasClass("btn")||(a=a.closest(".btn"));a.button("toggle")})}(window.jQuery);
!function(c){var a=function(a,b){this.$element=c(a);this.options=b;this.options.slide&&this.slide(this.options.slide);"hover"==this.options.pause&&this.$element.on("mouseenter",c.proxy(this.pause,this)).on("mouseleave",c.proxy(this.cycle,this))};a.prototype={cycle:function(a){a||(this.paused=!1);this.options.interval&&!this.paused&&(this.interval=setInterval(c.proxy(this.next,this),this.options.interval));return this},to:function(a){var b=this.$element.find(".item.active"),d=b.parent().children(),
b=d.index(b),f=this;if(!(a>d.length-1||0>a))return this.sliding?this.$element.one("slid",function(){f.to(a)}):b==a?this.pause().cycle():this.slide(a>b?"next":"prev",c(d[a]))},pause:function(a){a||(this.paused=!0);this.$element.find(".next, .prev").length&&c.support.transition.end&&(this.$element.trigger(c.support.transition.end),this.cycle());clearInterval(this.interval);this.interval=null;return this},next:function(){if(!this.sliding)return this.slide("next")},prev:function(){if(!this.sliding)return this.slide("prev")},
slide:function(a,b){var d=this.$element.find(".item.active"),f=b||d[a](),g=this.interval,h="next"==a?"left":"right",m="next"==a?"first":"last",p=this;this.sliding=!0;g&&this.pause();f=f.length?f:this.$element.find(".item")[m]();m=c.Event("slide",{relatedTarget:f[0]});if(!f.hasClass("active")){if(c.support.transition&&this.$element.hasClass("slide")){this.$element.trigger(m);if(m.isDefaultPrevented())return;f.addClass(a);f[0].offsetWidth;d.addClass(h);f.addClass(h);this.$element.one(c.support.transition.end,
function(){f.removeClass([a,h].join(" ")).addClass("active");d.removeClass(["active",h].join(" "));p.sliding=!1;setTimeout(function(){p.$element.trigger("slid")},0)})}else{this.$element.trigger(m);if(m.isDefaultPrevented())return;d.removeClass("active");f.addClass("active");this.sliding=!1;this.$element.trigger("slid")}g&&this.cycle();return this}}};c.fn.carousel=function(e){return this.each(function(){var b=c(this),d=b.data("carousel"),f=c.extend({},c.fn.carousel.defaults,"object"==typeof e&&e),
g="string"==typeof e?e:f.slide;d||b.data("carousel",d=new a(this,f));if("number"==typeof e)d.to(e);else if(g)d[g]();else f.interval&&d.cycle()})};c.fn.carousel.defaults={interval:5E3,pause:"hover"};c.fn.carousel.Constructor=a;c(document).on("click.carousel.data-api","[data-slide]",function(a){var b=c(this),d,f=c(b.attr("data-target")||(d=b.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"")),b=!f.data("carousel")&&c.extend({},f.data(),b.data());f.carousel(b);a.preventDefault()})}(window.jQuery);
!function(c){var a=function(a,b){this.$element=c(a);this.options=c.extend({},c.fn.collapse.defaults,b);this.options.parent&&(this.$parent=c(this.options.parent));this.options.toggle&&this.toggle()};a.prototype={constructor:a,dimension:function(){return this.$element.hasClass("width")?"width":"height"},show:function(){var a,b,d,f;if(!this.transitioning){a=this.dimension();b=c.camelCase(["scroll",a].join("-"));if((d=this.$parent&&this.$parent.find("> .accordion-group > .in"))&&d.length){if((f=d.data("collapse"))&&
f.transitioning)return;d.collapse("hide");f||d.data("collapse",null)}this.$element[a](0);this.transition("addClass",c.Event("show"),"shown");c.support.transition&&this.$element[a](this.$element[0][b])}},hide:function(){var a;this.transitioning||(a=this.dimension(),this.reset(this.$element[a]()),this.transition("removeClass",c.Event("hide"),"hidden"),this.$element[a](0))},reset:function(a){var b=this.dimension();this.$element.removeClass("collapse")[b](a||"auto")[0].offsetWidth;this.$element[null!==
a?"addClass":"removeClass"]("collapse");return this},transition:function(a,b,d){var f=this,g=function(){"show"==b.type&&f.reset();f.transitioning=0;f.$element.trigger(d)};this.$element.trigger(b);b.isDefaultPrevented()||(this.transitioning=1,this.$element[a]("in"),c.support.transition&&this.$element.hasClass("collapse")?this.$element.one(c.support.transition.end,g):g())},toggle:function(){this[this.$element.hasClass("in")?"hide":"show"]()}};c.fn.collapse=function(e){return this.each(function(){var b=
c(this),d=b.data("collapse"),f="object"==typeof e&&e;d||b.data("collapse",d=new a(this,f));if("string"==typeof e)d[e]()})};c.fn.collapse.defaults={toggle:!0};c.fn.collapse.Constructor=a;c(document).on("click.collapse.data-api","[data-toggle=collapse]",function(a){var b=c(this),d;a=b.attr("data-target")||a.preventDefault()||(d=b.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"");d=c(a).data("collapse")?"toggle":b.data();b[c(a).hasClass("in")?"addClass":"removeClass"]("collapsed");c(a).collapse(d)})}(window.jQuery);
!function(c){function a(){c("[data-toggle=dropdown]").each(function(){e(c(this)).removeClass("open")})}function e(b){var a=b.attr("data-target");a||(a=(a=b.attr("href"))&&/#/.test(a)&&a.replace(/.*(?=#[^\s]*$)/,""));a=c(a);a.length||(a=b.parent());return a}var b=function(b){var a=c(b).on("click.dropdown.data-api",this.toggle);c("html").on("click.dropdown.data-api",function(){a.parent().removeClass("open")})};b.prototype={constructor:b,toggle:function(b){b=c(this);var f,g;if(!b.is(".disabled, :disabled"))return f=
e(b),g=f.hasClass("open"),a(),g||(f.toggleClass("open"),b.focus()),!1},keydown:function(b){var a,g,h;if(/(38|40|27)/.test(b.keyCode)&&(a=c(this),b.preventDefault(),b.stopPropagation(),!a.is(".disabled, :disabled"))){g=e(a);h=g.hasClass("open");if(!h||h&&27==b.keyCode)return a.click();a=c("[role=menu] li:not(.divider) a",g);a.length&&(g=a.index(a.filter(":focus")),38==b.keyCode&&0<g&&g--,40==b.keyCode&&g<a.length-1&&g++,~g||(g=0),a.eq(g).focus())}}};c.fn.dropdown=function(a){return this.each(function(){var e=
c(this),g=e.data("dropdown");g||e.data("dropdown",g=new b(this));"string"==typeof a&&g[a].call(e)})};c.fn.dropdown.Constructor=b;c(document);c("html").on("click.dropdown.data-api touchstart.dropdown.data-api",a);c("body").on("click.dropdown touchstart.dropdown.data-api",".dropdown",function(b){b.stopPropagation()}).on("click.dropdown.data-api touchstart.dropdown.data-api","[data-toggle=dropdown]",b.prototype.toggle).on("keydown.dropdown.data-api touchstart.dropdown.data-api","[data-toggle=dropdown], [role=menu]",
b.prototype.keydown)}(window.jQuery);
!function(c){var a=function(a,b){this.options=b;this.$element=c(a).delegate('[data-dismiss="modal"]',"click.dismiss.modal",c.proxy(this.hide,this));this.options.remote&&this.$element.find(".modal-body").load(this.options.remote)};a.prototype={constructor:a,toggle:function(){return this[this.isShown?"hide":"show"]()},show:function(){var a=this,b=c.Event("show");this.$element.trigger(b);this.isShown||b.isDefaultPrevented()||(this.isShown=!0,this.escape(),this.backdrop(function(){var b=c.support.transition&&
a.$element.hasClass("fade");a.$element.parent().length||a.$element.appendTo(document.body);a.$element.show();b&&a.$element[0].offsetWidth;a.$element.addClass("in").attr("aria-hidden",!1);a.enforceFocus();b?a.$element.one(c.support.transition.end,function(){a.$element.focus().trigger("shown")}):a.$element.focus().trigger("shown")}))},hide:function(a){a&&a.preventDefault();a=c.Event("hide");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=!1,this.escape(),c(document).off("focusin.modal"),
this.$element.removeClass("in").attr("aria-hidden",!0),c.support.transition&&this.$element.hasClass("fade")?this.hideWithTransition():this.hideModal())},enforceFocus:function(){var a=this;c(document).on("focusin.modal",function(b){a.$element[0]===b.target||a.$element.has(b.target).length||a.$element.focus()})},escape:function(){var a=this;if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.modal",function(b){27==b.which&&a.hide()});else this.isShown||this.$element.off("keyup.dismiss.modal")},
hideWithTransition:function(){var a=this,b=setTimeout(function(){a.$element.off(c.support.transition.end);a.hideModal()},500);this.$element.one(c.support.transition.end,function(){clearTimeout(b);a.hideModal()})},hideModal:function(a){this.$element.hide().trigger("hidden");this.backdrop()},removeBackdrop:function(){this.$backdrop.remove();this.$backdrop=null},backdrop:function(a){var b=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var d=c.support.transition&&b;this.$backdrop=
c('<div class="modal-backdrop '+b+'" />').appendTo(document.body);this.$backdrop.click("static"==this.options.backdrop?c.proxy(this.$element[0].focus,this.$element[0]):c.proxy(this.hide,this));d&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");d?this.$backdrop.one(c.support.transition.end,a):a()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),c.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(c.support.transition.end,c.proxy(this.removeBackdrop,
this)):this.removeBackdrop()):a&&a()}};c.fn.modal=function(e){return this.each(function(){var b=c(this),d=b.data("modal"),f=c.extend({},c.fn.modal.defaults,b.data(),"object"==typeof e&&e);d||b.data("modal",d=new a(this,f));if("string"==typeof e)d[e]();else f.show&&d.show()})};c.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};c.fn.modal.Constructor=a;c(document).on("click.modal.data-api",'[data-toggle="modal"]',function(a){var b=c(this),d=b.attr("href"),f=c(b.attr("data-target")||d&&d.replace(/.*(?=#[^\s]+$)/,
"")),d=f.data("modal")?"toggle":c.extend({remote:!/#/.test(d)&&d},f.data(),b.data());a.preventDefault();f.modal(d).one("hide",function(){b.focus()})})}(window.jQuery);
!function(c){var a=function(a,b){this.init("tooltip",a,b)};a.prototype={constructor:a,init:function(a,b,d){this.type=a;this.$element=c(b);this.options=this.getOptions(d);this.enabled=!0;if("click"==this.options.trigger)this.$element.on("click."+this.type,this.options.selector,c.proxy(this.toggle,this));else"manual"!=this.options.trigger&&(a="hover"==this.options.trigger?"mouseenter":"focus",b="hover"==this.options.trigger?"mouseleave":"blur",this.$element.on(a+"."+this.type,this.options.selector,
c.proxy(this.enter,this)),this.$element.on(b+"."+this.type,this.options.selector,c.proxy(this.leave,this)));this.options.selector?this._options=c.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()},getOptions:function(a){a=c.extend({},c.fn[this.type].defaults,a,this.$element.data());a.delay&&"number"==typeof a.delay&&(a.delay={show:a.delay,hide:a.delay});return a},enter:function(a){var b=c(a.currentTarget)[this.type](this._options).data(this.type);if(!b.options.delay||!b.options.delay.show)return b.show();
clearTimeout(this.timeout);b.hoverState="in";this.timeout=setTimeout(function(){"in"==b.hoverState&&b.show()},b.options.delay.show)},leave:function(a){var b=c(a.currentTarget)[this.type](this._options).data(this.type);this.timeout&&clearTimeout(this.timeout);if(!b.options.delay||!b.options.delay.hide)return b.hide();b.hoverState="out";this.timeout=setTimeout(function(){"out"==b.hoverState&&b.hide()},b.options.delay.hide)},show:function(){var a,b,c,f,g,h,m;if(this.hasContent()&&this.enabled){a=this.tip();
this.setContent();this.options.animation&&a.addClass("fade");h="function"==typeof this.options.placement?this.options.placement.call(this,a[0],this.$element[0]):this.options.placement;b=/in/.test(h);a.detach().css({top:0,left:0,display:"block"}).insertAfter(this.$element);c=this.getPosition(b);f=a[0].offsetWidth;g=a[0].offsetHeight;switch(b?h.split(" ")[1]:h){case "bottom":m={top:c.top+c.height,left:c.left+c.width/2-f/2};break;case "top":m={top:c.top-g,left:c.left+c.width/2-f/2};break;case "left":m=
{top:c.top+c.height/2-g/2,left:c.left-f};break;case "right":m={top:c.top+c.height/2-g/2,left:c.left+c.width}}a.offset(m).addClass(h).addClass("in")}},setContent:function(){var a=this.tip(),b=this.getTitle();a.find(".tooltip-inner")[this.options.html?"html":"text"](b);a.removeClass("fade in top bottom left right")},hide:function(){function a(){var d=setTimeout(function(){b.off(c.support.transition.end).detach()},500);b.one(c.support.transition.end,function(){clearTimeout(d);b.detach()})}var b=this.tip();
b.removeClass("in");c.support.transition&&this.$tip.hasClass("fade")?a():b.detach();return this},fixTitle:function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||"").removeAttr("title")},hasContent:function(){return this.getTitle()},getPosition:function(a){return c.extend({},a?{top:0,left:0}:this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight})},getTitle:function(){var a=
this.$element,b=this.options;return a.attr("data-original-title")||("function"==typeof b.title?b.title.call(a[0]):b.title)},tip:function(){return this.$tip=this.$tip||c(this.options.template)},validate:function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(a){a=c(a.currentTarget)[this.type](this._options).data(this.type);a[a.tip().hasClass("in")?
"hide":"show"]()},destroy:function(){this.hide().$element.off("."+this.type).removeData(this.type)}};c.fn.tooltip=function(e){return this.each(function(){var b=c(this),d=b.data("tooltip"),f="object"==typeof e&&e;d||b.data("tooltip",d=new a(this,f));if("string"==typeof e)d[e]()})};c.fn.tooltip.Constructor=a;c.fn.tooltip.defaults={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover",title:"",
delay:0,html:!1}}(window.jQuery);
!function(c){var a=function(a,b){this.init("popover",a,b)};a.prototype=c.extend({},c.fn.tooltip.Constructor.prototype,{constructor:a,setContent:function(){var a=this.tip(),b=this.getTitle(),c=this.getContent();a.find(".popover-title")[this.options.html?"html":"text"](b);a.find(".popover-content > *")[this.options.html?"html":"text"](c);a.removeClass("fade top bottom left right in")},hasContent:function(){return this.getTitle()||this.getContent()},getContent:function(){var a=this.$element,b=this.options;
return a.attr("data-content")||("function"==typeof b.content?b.content.call(a[0]):b.content)},tip:function(){this.$tip||(this.$tip=c(this.options.template));return this.$tip},destroy:function(){this.hide().$element.off("."+this.type).removeData(this.type)}});c.fn.popover=function(e){return this.each(function(){var b=c(this),d=b.data("popover"),f="object"==typeof e&&e;d||b.data("popover",d=new a(this,f));if("string"==typeof e)d[e]()})};c.fn.popover.Constructor=a;c.fn.popover.defaults=c.extend({},c.fn.tooltip.defaults,
{placement:"right",trigger:"click",content:"",template:'<div class="popover"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"><p></p></div></div></div>'})}(window.jQuery);
!function(c){function a(a,b){var d=c.proxy(this.process,this),f=c(a).is("body")?c(window):c(a),g;this.options=c.extend({},c.fn.scrollspy.defaults,b);this.$scrollElement=f.on("scroll.scroll-spy.data-api",d);this.selector=(this.options.target||(g=c(a).attr("href"))&&g.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.$body=c("body");this.refresh();this.process()}a.prototype={constructor:a,refresh:function(){var a=this;this.offsets=c([]);this.targets=c([]);this.$body.find(this.selector).map(function(){var b=
c(this),b=b.data("target")||b.attr("href"),a=/^#\w/.test(b)&&c(b);return a&&a.length&&[[a.position().top,b]]||null}).sort(function(b,a){return b[0]-a[0]}).each(function(){a.offsets.push(this[0]);a.targets.push(this[1])})},process:function(){var a=this.$scrollElement.scrollTop()+this.options.offset,b=(this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight)-this.$scrollElement.height(),c=this.offsets,f=this.targets,g=this.activeTarget,h;if(a>=b)return g!=(h=f.last()[0])&&this.activate(h);for(h=
c.length;h--;)g!=f[h]&&a>=c[h]&&(!c[h+1]||a<=c[h+1])&&this.activate(f[h])},activate:function(a){this.activeTarget=a;c(this.selector).parent(".active").removeClass("active");a=c(this.selector+'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parent("li").addClass("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").addClass("active"));a.trigger("activate")}};c.fn.scrollspy=function(e){return this.each(function(){var b=c(this),d=b.data("scrollspy"),f="object"==typeof e&&e;
d||b.data("scrollspy",d=new a(this,f));if("string"==typeof e)d[e]()})};c.fn.scrollspy.Constructor=a;c.fn.scrollspy.defaults={offset:10};c(window).on("load",function(){c('[data-spy="scroll"]').each(function(){var a=c(this);a.scrollspy(a.data())})})}(window.jQuery);
!function(c){var a=function(a){this.element=c(a)};a.prototype={constructor:a,show:function(){var a=this.element,b=a.closest("ul:not(.dropdown-menu)"),d=a.attr("data-target"),f,g;d||(d=(d=a.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,""));a.parent("li").hasClass("active")||(f=b.find(".active:last a")[0],g=c.Event("show",{relatedTarget:f}),a.trigger(g),g.isDefaultPrevented()||(d=c(d),this.activate(a.parent("li"),b),this.activate(d,d.parent(),function(){a.trigger({type:"shown",relatedTarget:f})})))},activate:function(a,
b,d){function f(){g.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");h?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");d&&d()}var g=b.find("> .active"),h=d&&c.support.transition&&g.hasClass("fade");h?g.one(c.support.transition.end,f):f();g.removeClass("in")}};c.fn.tab=function(e){return this.each(function(){var b=c(this),d=b.data("tab");d||b.data("tab",d=new a(this));
if("string"==typeof e)d[e]()})};c.fn.tab.Constructor=a;c(document).on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();c(this).tab("show")})}(window.jQuery);
!function(c){var a=function(a,b){this.$element=c(a);this.options=c.extend({},c.fn.typeahead.defaults,b);this.matcher=this.options.matcher||this.matcher;this.sorter=this.options.sorter||this.sorter;this.highlighter=this.options.highlighter||this.highlighter;this.updater=this.options.updater||this.updater;this.$menu=c(this.options.menu).appendTo("body");this.source=this.options.source;this.shown=!1;this.listen()};a.prototype={constructor:a,select:function(){var a=this.$menu.find(".active").attr("data-value");
this.$element.val(this.updater(a)).change();return this.hide()},updater:function(a){return a},show:function(){var a=c.extend({},this.$element.offset(),{height:this.$element[0].offsetHeight});this.$menu.css({top:a.top+a.height,left:a.left});this.$menu.show();this.shown=!0;return this},hide:function(){this.$menu.hide();this.shown=!1;return this},lookup:function(a){this.query=this.$element.val();return!this.query||this.query.length<this.options.minLength?this.shown?this.hide():this:(a=c.isFunction(this.source)?
this.source(this.query,c.proxy(this.process,this)):this.source)?this.process(a):this},process:function(a){var b=this;a=c.grep(a,function(a){return b.matcher(a)});a=this.sorter(a);return a.length?this.render(a.slice(0,this.options.items)).show():this.shown?this.hide():this},matcher:function(a){return~a.toLowerCase().indexOf(this.query.toLowerCase())},sorter:function(a){for(var b=[],c=[],f=[],g;g=a.shift();)g.toLowerCase().indexOf(this.query.toLowerCase())?~g.indexOf(this.query)?c.push(g):f.push(g):
b.push(g);return b.concat(c,f)},highlighter:function(a){var b=this.query.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&");return a.replace(new RegExp("("+b+")","ig"),function(b,a){return"<strong>"+a+"</strong>"})},render:function(a){var b=this;a=c(a).map(function(a,e){a=c(b.options.item).attr("data-value",e);a.find("a").html(b.highlighter(e));return a[0]});a.first().addClass("active");this.$menu.html(a);return this},next:function(a){a=this.$menu.find(".active").removeClass("active").next();a.length||
(a=c(this.$menu.find("li")[0]));a.addClass("active")},prev:function(a){a=this.$menu.find(".active").removeClass("active").prev();a.length||(a=this.$menu.find("li").last());a.addClass("active")},listen:function(){this.$element.on("blur",c.proxy(this.blur,this)).on("keypress",c.proxy(this.keypress,this)).on("keyup",c.proxy(this.keyup,this));if(this.eventSupported("keydown"))this.$element.on("keydown",c.proxy(this.keydown,this));this.$menu.on("click",c.proxy(this.click,this)).on("mouseenter","li",c.proxy(this.mouseenter,
this))},eventSupported:function(a){var b=a in this.$element;b||(this.$element.setAttribute(a,"return;"),b="function"===typeof this.$element[a]);return b},move:function(a){if(this.shown){switch(a.keyCode){case 9:case 13:case 27:a.preventDefault();break;case 38:a.preventDefault();this.prev();break;case 40:a.preventDefault(),this.next()}a.stopPropagation()}},keydown:function(a){this.suppressKeyPressRepeat=!~c.inArray(a.keyCode,[40,38,9,13,27]);this.move(a)},keypress:function(a){this.suppressKeyPressRepeat||
this.move(a)},keyup:function(a){switch(a.keyCode){case 40:case 38:case 16:case 17:case 18:break;case 9:case 13:if(!this.shown)return;this.select();break;case 27:if(!this.shown)return;this.hide();break;default:this.lookup()}a.stopPropagation();a.preventDefault()},blur:function(a){var b=this;setTimeout(function(){b.hide()},150)},click:function(a){a.stopPropagation();a.preventDefault();this.select()},mouseenter:function(a){this.$menu.find(".active").removeClass("active");c(a.currentTarget).addClass("active")}};
c.fn.typeahead=function(e){return this.each(function(){var b=c(this),d=b.data("typeahead"),f="object"==typeof e&&e;d||b.data("typeahead",d=new a(this,f));if("string"==typeof e)d[e]()})};c.fn.typeahead.defaults={source:[],items:8,menu:'<ul class="typeahead dropdown-menu"></ul>',item:'<li><a href="#"></a></li>',minLength:1};c.fn.typeahead.Constructor=a;c(document).on("focus.typeahead.data-api",'[data-provide="typeahead"]',function(a){var b=c(this);b.data("typeahead")||(a.preventDefault(),b.typeahead(b.data()))})}(window.jQuery);
!function(c){var a=function(a,b){this.options=c.extend({},c.fn.affix.defaults,b);this.$window=c(window).on("scroll.affix.data-api",c.proxy(this.checkPosition,this)).on("click.affix.data-api",c.proxy(function(){setTimeout(c.proxy(this.checkPosition,this),1)},this));this.$element=c(a);this.checkPosition()};a.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=c(document).height(),b=this.$window.scrollTop(),d=this.$element.offset(),f=this.options.offset,g=f.bottom,h=f.top;"object"!=
typeof f&&(g=h=f);"function"==typeof h&&(h=f.top());"function"==typeof g&&(g=f.bottom());a=null!=this.unpin&&b+this.unpin<=d.top?!1:null!=g&&d.top+this.$element.height()>=a-g?"bottom":null!=h&&b<=h?"top":!1;this.affixed!==a&&(this.affixed=a,this.unpin="bottom"==a?d.top-b:null,this.$element.removeClass("affix affix-top affix-bottom").addClass("affix"+(a?"-"+a:"")))}};c.fn.affix=function(e){return this.each(function(){var b=c(this),d=b.data("affix"),f="object"==typeof e&&e;d||b.data("affix",d=new a(this,
f));if("string"==typeof e)d[e]()})};c.fn.affix.Constructor=a;c.fn.affix.defaults={offset:0};c(window).on("load",function(){c('[data-spy="affix"]').each(function(){var a=c(this),b=a.data();b.offset=b.offset||{};b.offsetBottom&&(b.offset.bottom=b.offsetBottom);b.offsetTop&&(b.offset.top=b.offsetTop);a.affix(b)})})}(window.jQuery);
$(function(){var c=document.querySelector&&document.querySelector('meta[name="viewport"]'),a=navigator.userAgent,e=function(){c.content="width=device-width, minimum-scale=0.25, maximum-scale=1.6"};c&&/iPhone|iPad/.test(a)&&!/Opera Mini/.test(a)&&(c.content="width=device-width, minimum-scale=1.0, maximum-scale=1.0",document.addEventListener("gesturestart",e,!1));-1<navigator.userAgent.toLowerCase().indexOf("android")&&$(".sf-menu").responsiveMenu({autoArrows:!0})});
var ua=navigator.userAgent.toLocaleLowerCase(),regV=/ipod|ipad|iphone/gi,result=ua.match(regV),userScale="";result||(userScale=",user-scalable=0");document.write('<meta name="viewport" content="width=device-width,initial-scale=1.0'+userScale+'">');(function(c){c.fn.superfish=function(a){var b=c.fn.superfish,d=b.c,f=c(['<b class="',d.arrowClass,'"></b>'].join("")),g=function(){var a=c(this),b=m(a);clearTimeout(b.sfTimer);a.showSuperfishUl().siblings().hideSuperfishUl()},h=function(){var a=c(this),d=m(a),f=b.op;clearTimeout(d.sfTimer);d.sfTimer=setTimeout(function(){f.retainPath=-1<c.inArray(a[0],f.$path);a.hideSuperfishUl();f.$path.length&&1>a.parents(["li.",f.hoverClass].join("")).length&&g.call(f.$path)},f.delay)},m=function(a){a=a.parents(["ul.",
d.menuClass,":first"].join(""))[0];b.op=b.o[a.serial];return a};return this.each(function(){var m=this.serial=b.o.length,l=c.extend({},b.defaults,a);l.$path=c("li."+l.pathClass,this).slice(0,l.pathLevels).each(function(){c(this).addClass([l.hoverClass,d.bcClass].join(" ")).filter("li:has(ul)").removeClass(l.pathClass)});b.o[m]=b.op=l;c("li:has(ul)",this)[c.fn.hoverIntent&&!l.disableHI?"hoverIntent":"hover"](g,h).each(function(){l.autoArrows&&c(">a:first-child",this).addClass(d.anchorClass).append(f.clone())}).not("."+
d.bcClass).hideSuperfishUl();var q=c("a",this);q.each(function(a){q.eq(a).parents("li")});l.onInit.call(this)}).each(function(){var a=[d.menuClass];!b.op.dropShadows||c.browser.msie&&7>c.browser.version||a.push(d.shadowClass);c(this).addClass(a.join(" "))})};var a=c.fn.superfish;a.o=[];a.op={};a.IE7fix=function(){var e=a.op;c.browser.msie&&6<c.browser.version&&e.dropShadows&&void 0!=e.animation.opacity&&this.toggleClass(a.c.shadowClass+"-off")};a.c={bcClass:"sf-breadcrumb",menuClass:"sf-js-enabled",
anchorClass:"sf-with-ul",arrowClass:"sf-sub-indicator",shadowClass:"sf-shadow"};a.defaults={hoverClass:"sfHover",pathClass:"overideThisToUse",pathLevels:2,delay:800,animation:{height:"show"},speed:"normal",autoArrows:!0,dropShadows:!1,disableHI:!1,onInit:function(){},onBeforeShow:function(){},onShow:function(){},onHide:function(){}};c.fn.extend({hideSuperfishUl:function(){var e=a.op,b=!0===e.retainPath?e.$path:"";e.retainPath=!1;b=c(["li.",e.hoverClass].join(""),this).add(this).not(b).removeClass(e.hoverClass).find(">ul").hide();
e.onHide.call(b);return this},showSuperfishUl:function(){var c=a.op,b=this.not(".accorChild").addClass(c.hoverClass).find(">ul:hidden");a.IE7fix.call(b);c.onBeforeShow.call(b);b.animate(c.animation,c.speed,function(){a.IE7fix.call(b);c.onShow.call(b)});return this}})})(jQuery);$(function(){$(".sf-menu").superfish()});(function(c){c.flexslider=function(a,e){var b=c(a),d=c.extend({},c.flexslider.defaults,e),f=d.namespace,g="ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch,h=g?"touchend":"click",m="vertical"===d.direction,p=d.reverse,l=0<d.itemWidth,q="fade"===d.animation,k=""!==d.asNavFor,n={};c.data(a,"flexslider",b);n={init:function(){b.animating=!1;b.currentSlide=d.startAt;b.animatingTo=b.currentSlide;b.atEnd=0===b.currentSlide||b.currentSlide===b.last;b.containerSelector=d.selector.substr(0,
d.selector.search(" "));b.slides=c(d.selector,b);b.container=c(b.containerSelector,b);b.count=b.slides.length;b.syncExists=0<c(d.sync).length;"slide"===d.animation&&(d.animation="swing");b.prop=m?"top":"marginLeft";b.args={};b.manualPause=!1;var a;if(a=!d.video)if(a=!q)if(a=d.useCSS)a:{a=document.createElement("div");var f=["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"],e;for(e in f)if(void 0!==a.style[f[e]]){b.pfx=f[e].replace("Perspective","").toLowerCase();
b.prop="-"+b.pfx+"-transform";a=!0;break a}a=!1}b.transitions=a;""!==d.controlsContainer&&(b.controlsContainer=0<c(d.controlsContainer).length&&c(d.controlsContainer));""!==d.manualControls&&(b.manualControls=0<c(d.manualControls).length&&c(d.manualControls));d.randomize&&(b.slides.sort(function(){return Math.round(Math.random())-.5}),b.container.empty().append(b.slides));b.doMath();k&&n.asNav.setup();b.setup("init");d.controlNav&&n.controlNav.setup();d.directionNav&&n.directionNav.setup();d.keyboard&&
(1===c(b.containerSelector).length||d.multipleKeyboard)&&c(document).bind("keyup",function(a){a=a.keyCode;b.animating||39!==a&&37!==a||(a=39===a?b.getTarget("next"):37===a?b.getTarget("prev"):!1,b.flexAnimate(a,d.pauseOnAction))});d.mousewheel&&b.bind("mousewheel",function(a,c){a.preventDefault();var f=0>c?b.getTarget("next"):b.getTarget("prev");b.flexAnimate(f,d.pauseOnAction)});d.pausePlay&&n.pausePlay.setup();d.slideshow&&(d.pauseOnHover&&b.hover(function(){b.manualPlay||b.manualPause||b.pause()},
function(){b.manualPause||b.manualPlay||b.play()}),0<d.initDelay?setTimeout(b.play,d.initDelay):b.play());g&&d.touch&&n.touch();(!q||q&&d.smoothHeight)&&c(window).bind("resize focus",n.resize);setTimeout(function(){d.start(b)},200)},asNav:{setup:function(){b.asNav=!0;b.animatingTo=Math.floor(b.currentSlide/b.move);b.currentItem=b.currentSlide;b.slides.removeClass(f+"active-slide").eq(b.currentItem).addClass(f+"active-slide");b.slides.click(function(a){a.preventDefault();a=c(this);var f=a.index();
c(d.asNavFor).data("flexslider").animating||a.hasClass("active")||(b.direction=b.currentItem<f?"next":"prev",b.flexAnimate(f,d.pauseOnAction,!1,!0,!0))})}},controlNav:{setup:function(){b.manualControls?n.controlNav.setupManual():n.controlNav.setupPaging()},setupPaging:function(){var a=1,e;b.controlNavScaffold=c('<ol class="'+f+"control-nav "+f+("thumbnails"===d.controlNav?"control-thumbs":"control-paging")+'"></ol>');if(1<b.pagingCount)for(var m=0;m<b.pagingCount;m++)e="thumbnails"===d.controlNav?
'<img src="'+b.slides.eq(m).attr("data-thumb")+'"/>':"<a>"+a+"</a>",b.controlNavScaffold.append("<li>"+e+"</li>"),a++;b.controlsContainer?c(b.controlsContainer).append(b.controlNavScaffold):b.append(b.controlNavScaffold);n.controlNav.set();n.controlNav.active();b.controlNavScaffold.delegate("a, img",h,function(a){a.preventDefault();a=c(this);var e=b.controlNav.index(a);a.hasClass(f+"active")||(b.direction=e>b.currentSlide?"next":"prev",b.flexAnimate(e,d.pauseOnAction))});g&&b.controlNavScaffold.delegate("a",
"click touchstart",function(a){a.preventDefault()})},setupManual:function(){b.controlNav=b.manualControls;n.controlNav.active();b.controlNav.live(h,function(a){a.preventDefault();a=c(this);var e=b.controlNav.index(a);a.hasClass(f+"active")||(e>b.currentSlide?b.direction="next":b.direction="prev",b.flexAnimate(e,d.pauseOnAction))});g&&b.controlNav.live("click touchstart",function(a){a.preventDefault()})},set:function(){b.controlNav=c("."+f+"control-nav li "+("thumbnails"===d.controlNav?"img":"a"),
b.controlsContainer?b.controlsContainer:b)},active:function(){b.controlNav.removeClass(f+"active").eq(b.animatingTo).addClass(f+"active")},update:function(a,d){1<b.pagingCount&&"add"===a?b.controlNavScaffold.append(c("<li><a>"+b.count+"</a></li>")):1===b.pagingCount?b.controlNavScaffold.find("li").remove():b.controlNav.eq(d).closest("li").remove();n.controlNav.set();1<b.pagingCount&&b.pagingCount!==b.controlNav.length?b.update(d,a):n.controlNav.active()}},directionNav:{setup:function(){var a=c('<ul class="'+
f+'direction-nav"><li><a class="'+f+'prev" href="#">'+d.prevText+'</a></li><li><a class="'+f+'next" href="#">'+d.nextText+"</a></li></ul>");b.controlsContainer?(c(b.controlsContainer).append(a),b.directionNav=c("."+f+"direction-nav li a",b.controlsContainer)):(b.append(a),b.directionNav=c("."+f+"direction-nav li a",b));n.directionNav.update();b.directionNav.bind(h,function(a){a.preventDefault();a=c(this).hasClass(f+"next")?b.getTarget("next"):b.getTarget("prev");b.flexAnimate(a,d.pauseOnAction)});
g&&b.directionNav.bind("click touchstart",function(a){a.preventDefault()})},update:function(){var a=f+"disabled";1===b.pagingCount?b.directionNav.addClass(a):d.animationLoop?b.directionNav.removeClass(a):0===b.animatingTo?b.directionNav.removeClass(a).filter("."+f+"prev").addClass(a):b.animatingTo===b.last?b.directionNav.removeClass(a).filter("."+f+"next").addClass(a):b.directionNav.removeClass(a)}},pausePlay:{setup:function(){var a=c('<div class="'+f+'pauseplay"><a></a></div>');b.controlsContainer?
(b.controlsContainer.append(a),b.pausePlay=c("."+f+"pauseplay a",b.controlsContainer)):(b.append(a),b.pausePlay=c("."+f+"pauseplay a",b));n.pausePlay.update(d.slideshow?f+"pause":f+"play");b.pausePlay.bind(h,function(a){a.preventDefault();c(this).hasClass(f+"pause")?(b.manualPause=!0,b.manualPlay=!1,b.pause()):(b.manualPause=!1,b.manualPlay=!0,b.play())});g&&b.pausePlay.bind("click touchstart",function(a){a.preventDefault()})},update:function(a){"play"===a?b.pausePlay.removeClass(f+"pause").addClass(f+
"play").text(d.playText):b.pausePlay.removeClass(f+"play").addClass(f+"pause").text(d.pauseText)}},touch:function(){function c(a){k=m?e-a.touches[0].pageY:e-a.touches[0].pageX;z=m?Math.abs(k)<Math.abs(a.touches[0].pageX-g):Math.abs(k)<Math.abs(a.touches[0].pageY-g);if(!z||500<Number(new Date)-w)a.preventDefault(),!q&&b.transitions&&(d.animationLoop||(k/=0===b.currentSlide&&0>k||b.currentSlide===b.last&&0<k?Math.abs(k)/n+2:1),b.setProps(h+k,"setTouch"))}function f(){a.removeEventListener("touchmove",
c,!1);if(b.animatingTo===b.currentSlide&&!z&&null!==k){var m=p?-k:k,l=0<m?b.getTarget("next"):b.getTarget("prev");b.canAdvance(l)&&(550>Number(new Date)-w&&50<Math.abs(m)||Math.abs(m)>n/2)?b.flexAnimate(l,d.pauseOnAction):q||b.flexAnimate(b.currentSlide,d.pauseOnAction,!0)}a.removeEventListener("touchend",f,!1);h=k=g=e=null}var e,g,h,n,k,w,z=!1;a.addEventListener("touchstart",function(k){b.animating?k.preventDefault():1===k.touches.length&&(b.pause(),n=m?b.h:b.w,w=Number(new Date),h=l&&p&&b.animatingTo===
b.last?0:l&&p?b.limit-(b.itemW+d.itemMargin)*b.move*b.animatingTo:l&&b.currentSlide===b.last?b.limit:l?(b.itemW+d.itemMargin)*b.move*b.currentSlide:p?(b.last-b.currentSlide+b.cloneOffset)*n:(b.currentSlide+b.cloneOffset)*n,e=m?k.touches[0].pageY:k.touches[0].pageX,g=m?k.touches[0].pageX:k.touches[0].pageY,a.addEventListener("touchmove",c,!1),a.addEventListener("touchend",f,!1))},!1)},resize:function(){!b.animating&&b.is(":visible")&&(l||b.doMath(),q?n.smoothHeight():l?(b.slides.width(b.computedW),
b.update(b.pagingCount),b.setProps()):m?(b.viewport.height(b.h),b.setProps(b.h,"setTotal")):(d.smoothHeight&&n.smoothHeight(),b.newSlides.width(b.computedW),b.setProps(b.computedW,"setTotal")))},smoothHeight:function(a){if(!m||q){var c=q?b:b.viewport;a?c.animate({height:b.slides.eq(b.animatingTo).height()},a):c.height(b.slides.eq(b.animatingTo).height())}},sync:function(a){var f=c(d.sync).data("flexslider"),e=b.animatingTo;switch(a){case "animate":f.flexAnimate(e,d.pauseOnAction,!1,!0);break;case "play":f.playing||
f.asNav||f.play();break;case "pause":f.pause()}}};b.flexAnimate=function(a,e,h,y,u){k&&1===b.pagingCount&&(b.direction=b.currentItem<a?"next":"prev");if(!b.animating&&(b.canAdvance(a,u)||h)&&b.is(":visible")){if(k&&y)if(h=c(d.asNavFor).data("flexslider"),b.atEnd=0===a||a===b.count-1,h.flexAnimate(a,!0,!1,!0,u),b.direction=b.currentItem<a?"next":"prev",h.direction=b.direction,Math.ceil((a+1)/b.visible)-1!==b.currentSlide&&0!==a)b.currentItem=a,b.slides.removeClass(f+"active-slide").eq(a).addClass(f+
"active-slide"),a=Math.floor(a/b.visible);else return b.currentItem=a,b.slides.removeClass(f+"active-slide").eq(a).addClass(f+"active-slide"),!1;b.animating=!0;b.animatingTo=a;d.before(b);e&&b.pause();b.syncExists&&!u&&n.sync("animate");d.controlNav&&n.controlNav.active();l||b.slides.removeClass(f+"active-slide").eq(a).addClass(f+"active-slide");b.atEnd=0===a||a===b.last;d.directionNav&&n.directionNav.update();a===b.last&&(d.end(b),d.animationLoop||b.pause());if(q)g?(b.slides.eq(b.currentSlide).css({opacity:0,
zIndex:1}),b.slides.eq(a).css({opacity:1,zIndex:2}),b.animating=!1,b.currentSlide=b.animatingTo):(b.slides.eq(b.currentSlide).fadeOut(d.animationSpeed,d.easing),b.slides.eq(a).fadeIn(d.animationSpeed,d.easing,b.wrapup));else{var t=m?b.slides.filter(":first").height():b.computedW;l?(a=d.itemWidth>b.w?2*d.itemMargin:d.itemMargin,a=(b.itemW+a)*b.move*b.animatingTo,a=a>b.limit&&1!==b.visible?b.limit:a):a=0===b.currentSlide&&a===b.count-1&&d.animationLoop&&"next"!==b.direction?p?(b.count+b.cloneOffset)*
t:0:b.currentSlide===b.last&&0===a&&d.animationLoop&&"prev"!==b.direction?p?0:(b.count+1)*t:p?(b.count-1-a+b.cloneOffset)*t:(a+b.cloneOffset)*t;b.setProps(a,"",d.animationSpeed);b.transitions?(d.animationLoop&&b.atEnd||(b.animating=!1,b.currentSlide=b.animatingTo),b.container.unbind("webkitTransitionEnd transitionend"),b.container.bind("webkitTransitionEnd transitionend",function(){b.wrapup(t)})):b.container.animate(b.args,d.animationSpeed,d.easing,function(){b.wrapup(t)})}d.smoothHeight&&n.smoothHeight(d.animationSpeed)}};
b.wrapup=function(a){!q&&!l&&(0===b.currentSlide&&b.animatingTo===b.last&&d.animationLoop?b.setProps(a,"jumpEnd"):b.currentSlide===b.last&&0===b.animatingTo&&d.animationLoop&&b.setProps(a,"jumpStart"));b.animating=!1;b.currentSlide=b.animatingTo;d.after(b)};b.animateSlides=function(){b.animating||b.flexAnimate(b.getTarget("next"))};b.pause=function(){clearInterval(b.animatedSlides);b.playing=!1;d.pausePlay&&n.pausePlay.update("play");b.syncExists&&n.sync("pause")};b.play=function(){b.animatedSlides=
setInterval(b.animateSlides,d.slideshowSpeed);b.playing=!0;d.pausePlay&&n.pausePlay.update("pause");b.syncExists&&n.sync("play")};b.canAdvance=function(a,c){var f=k?b.pagingCount-1:b.last;return c?!0:k&&b.currentItem===b.count-1&&0===a&&"prev"===b.direction?!0:k&&0===b.currentItem&&a===b.pagingCount-1&&"next"!==b.direction?!1:a!==b.currentSlide||k?d.animationLoop?!0:b.atEnd&&0===b.currentSlide&&a===f&&"next"!==b.direction?!1:b.atEnd&&b.currentSlide===f&&0===a&&"next"===b.direction?!1:!0:!1};b.getTarget=
function(a){b.direction=a;return"next"===a?b.currentSlide===b.last?0:b.currentSlide+1:0===b.currentSlide?b.last:b.currentSlide-1};b.setProps=function(a,c,f){var e,g=a?a:(b.itemW+d.itemMargin)*b.move*b.animatingTo;e=-1*function(){if(l)return"setTouch"===c?a:p&&b.animatingTo===b.last?0:p?b.limit-(b.itemW+d.itemMargin)*b.move*b.animatingTo:b.animatingTo===b.last?b.limit:g;switch(c){case "setTotal":return p?(b.count-1-b.currentSlide+b.cloneOffset)*a:(b.currentSlide+b.cloneOffset)*a;case "setTouch":return a;
case "jumpEnd":return p?a:b.count*a;case "jumpStart":return p?b.count*a:a;default:return a}}()+"px";b.transitions&&(e=m?"translate3d(0,"+e+",0)":"translate3d("+e+",0,0)",f=void 0!==f?f/1E3+"s":"0s",b.container.css("-"+b.pfx+"-transition-duration",f));b.args[b.prop]=e;(b.transitions||void 0===f)&&b.container.css(b.args)};b.setup=function(a){if(q)b.slides.css({width:"100%","float":"left",marginRight:"-100%",position:"relative"}),"init"===a&&(g?b.slides.css({opacity:0,display:"block",webkitTransition:"opacity "+
d.animationSpeed/1E3+"s ease",zIndex:1}).eq(b.currentSlide).css({opacity:1,zIndex:2}):b.slides.eq(b.currentSlide).fadeIn(d.animationSpeed,d.easing)),d.smoothHeight&&n.smoothHeight();else{var e,h;"init"===a&&(b.viewport=c('<div class="'+f+'viewport"></div>').css({overflow:"hidden",position:"relative"}).appendTo(b).append(b.container),b.cloneCount=0,b.cloneOffset=0,p&&(h=c.makeArray(b.slides).reverse(),b.slides=c(h),b.container.empty().append(b.slides)));d.animationLoop&&!l&&(b.cloneCount=2,b.cloneOffset=
1,"init"!==a&&b.container.find(".clone").remove(),b.container.append(b.slides.first().clone().addClass("clone")).prepend(b.slides.last().clone().addClass("clone")));b.newSlides=c(d.selector,b);e=p?b.count-1-b.currentSlide+b.cloneOffset:b.currentSlide+b.cloneOffset;m&&!l?(b.container.height(200*(b.count+b.cloneCount)+"%").css("position","absolute").width("100%"),setTimeout(function(){b.newSlides.css({display:"block"});b.doMath();b.viewport.height(b.h);b.setProps(e*b.h,"init")},"init"===a?100:0)):(b.container.width(200*
(b.count+b.cloneCount)+"%"),b.setProps(e*b.computedW,"init"),setTimeout(function(){b.doMath();b.newSlides.css({width:b.computedW,"float":"left",display:"block"});d.smoothHeight&&n.smoothHeight()},"init"===a?100:0))}l||b.slides.removeClass(f+"active-slide").eq(b.currentSlide).addClass(f+"active-slide")};b.doMath=function(){var a=b.slides.first(),c=d.itemMargin,f=d.minItems,e=d.maxItems;b.w=b.width();b.h=a.height();b.boxPadding=a.outerWidth()-a.width();l?(b.itemT=d.itemWidth+c,b.minW=f?f*b.itemT:b.w,
b.maxW=e?e*b.itemT:b.w,b.itemW=b.minW>b.w?(b.w-c*f)/f:b.maxW<b.w?(b.w-c*e)/e:d.itemWidth>b.w?b.w:d.itemWidth,b.visible=Math.floor(b.w/(b.itemW+c)),b.move=0<d.move&&d.move<b.visible?d.move:b.visible,b.pagingCount=Math.ceil((b.count-b.visible)/b.move+1),b.last=b.pagingCount-1,b.limit=1===b.pagingCount?0:d.itemWidth>b.w?(b.itemW+2*c)*b.count-b.w-c:(b.itemW+c)*b.count-b.w-c):(b.itemW=b.w,b.pagingCount=b.count,b.last=b.count-1);b.computedW=b.itemW-b.boxPadding};b.update=function(a,c){b.doMath();l||(a<
b.currentSlide?b.currentSlide+=1:a<=b.currentSlide&&0!==a&&--b.currentSlide,b.animatingTo=b.currentSlide);if(d.controlNav&&!b.manualControls)if("add"===c&&!l||b.pagingCount>b.controlNav.length)n.controlNav.update("add");else if("remove"===c&&!l||b.pagingCount<b.controlNav.length)l&&b.currentSlide>b.last&&(--b.currentSlide,--b.animatingTo),n.controlNav.update("remove",b.last);d.directionNav&&n.directionNav.update()};b.addSlide=function(a,f){var e=c(a);b.count+=1;b.last=b.count-1;m&&p?void 0!==f?b.slides.eq(b.count-
f).after(e):b.container.prepend(e):void 0!==f?b.slides.eq(f).before(e):b.container.append(e);b.update(f,"add");b.slides=c(d.selector+":not(.clone)",b);b.setup();d.added(b)};b.removeSlide=function(a){var f=isNaN(a)?b.slides.index(c(a)):a;--b.count;b.last=b.count-1;isNaN(a)?c(a,b.slides).remove():m&&p?b.slides.eq(b.last).remove():b.slides.eq(a).remove();b.doMath();b.update(f,"remove");b.slides=c(d.selector+":not(.clone)",b);b.setup();d.removed(b)};n.init()};c.flexslider.defaults={namespace:"flex-",
selector:".slides > li",animation:"fade",easing:"swing",direction:"horizontal",reverse:!1,animationLoop:!0,smoothHeight:!1,startAt:0,slideshow:!0,slideshowSpeed:7E3,animationSpeed:600,initDelay:0,randomize:!1,pauseOnAction:!0,pauseOnHover:!1,useCSS:!0,touch:!0,video:!1,controlNav:!0,directionNav:!0,prevText:"",nextText:"",keyboard:!0,multipleKeyboard:!1,mousewheel:!1,pausePlay:!1,pauseText:"",playText:"",controlsContainer:"",manualControls:"",sync:"",asNavFor:"",itemWidth:0,itemMargin:0,minItems:0,
maxItems:0,move:0,start:function(){},before:function(){},after:function(){},end:function(){},added:function(){},removed:function(){}};c.fn.flexslider=function(a){void 0===a&&(a={});if("object"===typeof a)return this.each(function(){var b=c(this),d=b.find(a.selector?a.selector:".slides > li");1===d.length?(d.fadeIn(400),a.start&&a.start(b)):void 0===b.data("flexslider")&&new c.flexslider(this,a)});var e=c(this).data("flexslider");switch(a){case "play":e.play();break;case "pause":e.pause();break;case "next":e.flexAnimate(e.getTarget("next"),
!0);break;case "prev":case "previous":e.flexAnimate(e.getTarget("prev"),!0);break;default:"number"===typeof a&&e.flexAnimate(a,!0)}}})(jQuery);(function(c){c.fn.kwicks=function(a){var e=c.extend({isVertical:!1,sticky:!1,defaultKwick:0,event:"mouseover",spacing:0,duration:500},a),b=e.isVertical?"height":"width",d=e.isVertical?"top":"left";return this.each(function(){container=c(this);var a=container.children("li"),g=a.eq(0).css(b).replace(/px/,"");e.max?e.min=(g*a.size()-e.max)/(a.size()-1):e.max=g*a.size()-e.min*(a.size()-1);e.isVertical?container.css({width:a.eq(0).css("width"),height:g*a.size()+e.spacing*(a.size()-1)+"px"}):container.css({width:g*
a.size()+e.spacing*(a.size()-1)+"px",height:a.eq(0).css("height")});var h=[];for(i=0;i<a.size();i++)for(h[i]=[],j=1;j<a.size()-1;j++)h[i][j]=i==j?j*e.min+j*e.spacing:(j<=i?j*e.min:(j-1)*e.min+e.max)+j*e.spacing;a.each(function(m){var p=c(this);0===m?p.css(d,"0px"):m==a.size()-1?p.css(e.isVertical?"bottom":"right","0px"):e.sticky?p.css(d,h[e.defaultKwick][m]):p.css(d,m*g+m*e.spacing);e.sticky&&(e.defaultKwick==m?(p.css(b,e.max+"px"),p.addClass("active")):p.css(b,e.min+"px"));p.css({margin:0,position:"absolute"});
p.bind(e.event,function(){var c=[],g=[];a.stop().removeClass("active");for(j=0;j<a.size();j++)c[j]=a.eq(j).css(b).replace(/px/,""),g[j]=a.eq(j).css(d).replace(/px/,"");var k={};k[b]=e.max;var n=e.max-c[m],A=c[m]/n;p.addClass("active").animate(k,{step:function(k){var p=0!=n?k/n-A:1;a.each(function(k){k!=m&&a.eq(k).css(b,c[k]-(c[k]-e.min)*p+"px");0<k&&k<a.size()-1&&a.eq(k).css(d,g[k]-(g[k]-h[m][k])*p+"px")})},duration:e.duration,easing:e.easing})})});e.sticky||container.bind("mouseleave",function(){var c=
[],h=[];a.removeClass("active").stop();for(i=0;i<a.size();i++)c[i]=a.eq(i).css(b).replace(/px/,""),h[i]=a.eq(i).css(d).replace(/px/,"");var l={};l[b]=g;var q=g-c[0];a.eq(0).animate(l,{step:function(k){k=0!=q?(k-c[0])/q:1;for(i=1;i<a.size();i++)a.eq(i).css(b,c[i]-(c[i]-g)*k+"px"),i<a.size()-1&&a.eq(i).css(d,h[i]-(h[i]-(i*g+i*e.spacing))*k+"px")},duration:e.duration,easing:e.easing})})})}})(jQuery);var Main=Main||{};
jQuery(window).load(function(){window.responsiveFlag=jQuery("#responsiveFlag").css("display");Main.gallery=new Gallery;jQuery(window).resize(function(){Main.gallery.update()})});
function Gallery(){container=jQuery(".flexslider");clone=container.clone(!1);this.init=function(){"block"==responsiveFlag?container.find(".slides").kwicks({max:754,spacing:0}).find("li > a").click(function(){return!1}):container.flexslider()};this.update=function(){var c=jQuery("#responsiveFlag").css("display");responsiveFlag!=c&&(responsiveFlag=c,container.replaceWith(clone),container=clone,clone=container.clone(!1),this.init())};this.init()};jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(c,a,e,b,d){return jQuery.easing[jQuery.easing.def](c,a,e,b,d)},easeInQuad:function(c,a,e,b,d){return b*(a/=d)*a+e},easeOutQuad:function(c,a,e,b,d){return-b*(a/=d)*(a-2)+e},easeInOutQuad:function(c,a,e,b,d){return 1>(a/=d/2)?b/2*a*a+e:-b/2*(--a*(a-2)-1)+e},easeInCubic:function(c,a,e,b,d){return b*(a/=d)*a*a+e},easeOutCubic:function(c,a,e,b,d){return b*((a=a/d-1)*a*a+1)+e},easeInOutCubic:function(c,a,e,b,d){return 1>(a/=d/2)?b/2*a*a*a+e:
b/2*((a-=2)*a*a+2)+e},easeInQuart:function(c,a,e,b,d){return b*(a/=d)*a*a*a+e},easeOutQuart:function(c,a,e,b,d){return-b*((a=a/d-1)*a*a*a-1)+e},easeInOutQuart:function(c,a,e,b,d){return 1>(a/=d/2)?b/2*a*a*a*a+e:-b/2*((a-=2)*a*a*a-2)+e},easeInQuint:function(c,a,e,b,d){return b*(a/=d)*a*a*a*a+e},easeOutQuint:function(c,a,e,b,d){return b*((a=a/d-1)*a*a*a*a+1)+e},easeInOutQuint:function(c,a,e,b,d){return 1>(a/=d/2)?b/2*a*a*a*a*a+e:b/2*((a-=2)*a*a*a*a+2)+e},easeInSine:function(c,a,e,b,d){return-b*Math.cos(a/
d*(Math.PI/2))+b+e},easeOutSine:function(c,a,e,b,d){return b*Math.sin(a/d*(Math.PI/2))+e},easeInOutSine:function(c,a,e,b,d){return-b/2*(Math.cos(Math.PI*a/d)-1)+e},easeInExpo:function(c,a,e,b,d){return 0==a?e:b*Math.pow(2,10*(a/d-1))+e},easeOutExpo:function(c,a,e,b,d){return a==d?e+b:b*(-Math.pow(2,-10*a/d)+1)+e},easeInOutExpo:function(c,a,e,b,d){return 0==a?e:a==d?e+b:1>(a/=d/2)?b/2*Math.pow(2,10*(a-1))+e:b/2*(-Math.pow(2,-10*--a)+2)+e},easeInCirc:function(c,a,e,b,d){return-b*(Math.sqrt(1-(a/=d)*
a)-1)+e},easeOutCirc:function(c,a,e,b,d){return b*Math.sqrt(1-(a=a/d-1)*a)+e},easeInOutCirc:function(c,a,e,b,d){return 1>(a/=d/2)?-b/2*(Math.sqrt(1-a*a)-1)+e:b/2*(Math.sqrt(1-(a-=2)*a)+1)+e},easeInElastic:function(c,a,e,b,d){c=1.70158;var f=0,g=b;if(0==a)return e;if(1==(a/=d))return e+b;f||(f=.3*d);g<Math.abs(b)?(g=b,c=f/4):c=f/(2*Math.PI)*Math.asin(b/g);return-(g*Math.pow(2,10*--a)*Math.sin(2*(a*d-c)*Math.PI/f))+e},easeOutElastic:function(c,a,e,b,d){c=1.70158;var f=0,g=b;if(0==a)return e;if(1==(a/=
d))return e+b;f||(f=.3*d);g<Math.abs(b)?(g=b,c=f/4):c=f/(2*Math.PI)*Math.asin(b/g);return g*Math.pow(2,-10*a)*Math.sin(2*(a*d-c)*Math.PI/f)+b+e},easeInOutElastic:function(c,a,e,b,d){c=1.70158;var f=0,g=b;if(0==a)return e;if(2==(a/=d/2))return e+b;f||(f=.3*d*1.5);g<Math.abs(b)?(g=b,c=f/4):c=f/(2*Math.PI)*Math.asin(b/g);return 1>a?-.5*g*Math.pow(2,10*--a)*Math.sin(2*(a*d-c)*Math.PI/f)+e:g*Math.pow(2,-10*--a)*Math.sin(2*(a*d-c)*Math.PI/f)*.5+b+e},easeInBack:function(c,a,e,b,d,f){void 0==f&&(f=1.70158);
return b*(a/=d)*a*((f+1)*a-f)+e},easeOutBack:function(c,a,e,b,d,f){void 0==f&&(f=1.70158);return b*((a=a/d-1)*a*((f+1)*a+f)+1)+e},easeInOutBack:function(c,a,e,b,d,f){void 0==f&&(f=1.70158);return 1>(a/=d/2)?b/2*a*a*(((f*=1.525)+1)*a-f)+e:b/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+e},easeInBounce:function(c,a,e,b,d){return b-jQuery.easing.easeOutBounce(c,d-a,0,b,d)+e},easeOutBounce:function(c,a,e,b,d){return(a/=d)<1/2.75?7.5625*b*a*a+e:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+.75)+e:a<2.5/2.75?b*(7.5625*(a-=
2.25/2.75)*a+.9375)+e:b*(7.5625*(a-=2.625/2.75)*a+.984375)+e},easeInOutBounce:function(c,a,e,b,d){return a<d/2?.5*jQuery.easing.easeInBounce(c,2*a,0,b,d)+e:.5*jQuery.easing.easeOutBounce(c,2*a-d,0,b,d)+.5*b+e}});(function(c){c.fn.forms=function(a){return this.each(function(){var e=c(this),b=e.data("forms")||{errorCl:"error",emptyCl:"empty",invalidCl:"invalid",notRequiredCl:"notRequired",successCl:"success",successShow:"4000",mailHandlerURL:"/mnaraghi.com/web/site/contact",ownerEmail:"support@template-help.com",stripHTML:!0,smtpMailServer:"localhost",targets:"input,textarea",controls:"a[data-type=reset],a[data-type=submit]",validate:!0,rx:{".name":{rx:/^[a-zA-Z'][a-zA-Z-' ]+[a-zA-Z']?$/,target:"input"},".state":{rx:/^[a-zA-Z'][a-zA-Z-' ]+[a-zA-Z']?$/,
target:"input"},".email":{rx:/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i,target:"input"},".phone":{rx:/^\+?(\d[\d\-\+\(\) ]{5,}\d$)/,target:"input"},".fax":{rx:/^\+?(\d[\d\-\+\(\) ]{5,}\d$)/,target:"input"},".message":{rx:/.{20}/,target:"textarea"}},preFu:function(){b.labels.each(function(){var a=
c(this),e=c(b.targets,this),g=e.val(),h=function(){var b=e.is("input")?(b=a.html().match(/value=['"](.+?)['"].+/),!!b&&!!b[1]&&b[1]):e.html();return""==g?g:b}();h!=g&&e.val(g=h||g);a.data({defVal:g});e.bind("focus",function(){e.val()==g&&(e.val(""),b.hideEmptyFu(a),a.removeClass(b.invalidCl))}).bind("blur",function(){b.validateFu(a);b.isEmpty(a)&&(e.val(g),b.hideErrorFu(a.removeClass(b.invalidCl)))}).bind("keyup",function(){a.hasClass(b.invalidCl)&&b.validateFu(a)});a.find("."+b.errorCl+",."+b.emptyCl).css({display:"block"}).hide()});
b.success=c("."+b.successCl,b.form).hide()},isRequired:function(a){return!a.hasClass(b.notRequiredCl)},isValid:function(a){var e=!0;c.each(b.rx,function(b,c){a.is(b)&&(e=c.rx.test(a.find(c.target).val()))});return e},isEmpty:function(a){var c;return""==(c=a.find(b.targets).val())||c==a.data("defVal")},validateFu:function(a){a.each(function(){var a=c(this),d=b.isRequired(a),e=b.isEmpty(a),m=b.isValid(a);e&&d?b.showEmptyFu(a.addClass(b.invalidCl)):b.hideEmptyFu(a.removeClass(b.invalidCl));e||(m?b.hideErrorFu(a.removeClass(b.invalidCl)):
b.showErrorFu(a.addClass(b.invalidCl)))})},getValFromLabel:function(a){var b=c("input,textarea",a).val(),e=a.data("defVal");return a.length?b==e?"nope":b:"nope"},submitFu:function(){b.validateFu(b.labels);if(0!=c("input#zarfeasal").val().length)return!1;var a=c("#_csrf").val();b.form.has("."+b.invalidCl).length||c.ajax({type:"POST",url:b.mailHandlerURL,data:{name:b.getValFromLabel(c(".name",b.form)),email:b.getValFromLabel(c(".email",b.form)),phone:b.getValFromLabel(c(".phone",b.form)),fax:b.getValFromLabel(c(".fax",
b.form)),state:b.getValFromLabel(c(".state",b.form)),message:b.getValFromLabel(c(".message",b.form)),owner_email:b.ownerEmail,stripHTML:b.stripHTML,_csrf:a},success:function(){b.showFu()},error:function(){c("#show-exception").slideDown()}})},showFu:function(){b.success.slideDown(function(){setTimeout(function(){b.success.slideUp();b.form.trigger("reset")},b.successShow)})},controlsFu:function(){c(b.controls,b.form).each(function(){var a=c(this);a.bind("click",function(){b.form.trigger(a.data("type"));
return!1})})},showErrorFu:function(a){a.find("."+b.errorCl).slideDown()},hideErrorFu:function(a){a.find("."+b.errorCl).slideUp()},showEmptyFu:function(a){a.find("."+b.emptyCl).slideDown();b.hideErrorFu(a)},hideEmptyFu:function(a){a.find("."+b.emptyCl).slideUp()},init:function(){b.form=b.me;b.labels=c("label",b.form);b.preFu();b.controlsFu();b.form.bind("submit",function(){b.validate?b.submitFu():b.form[0].submit();return!1}).bind("reset",function(){b.labels.removeClass(b.invalidCl);b.labels.each(function(){var a=
c(this);b.hideErrorFu(a);b.hideEmptyFu(a)})});b.form.trigger("reset")}};b.me||b.init(b.me=e.data({forms:b}));"object"==typeof a&&c.extend(b,a)})}})(jQuery);$(window).load(function(){$("#contact-form").forms({ownerEmail:"#"})});!function(c){"function"==typeof define&&define.amd?define(["jquery"],c):c("object"==typeof exports?require("jquery"):window.jQuery||window.Zepto)}(function(c){var a,e,b,d,f,g,h=function(){},m=!!window.jQuery,p=c(window),l=function(b,c){a.ev.on("mfp"+b+".mfp",c)},q=function(a,b,d,e){var f=document.createElement("div");return f.className="mfp-"+a,d&&(f.innerHTML=d),e?b&&b.appendChild(f):(f=c(f),b&&f.appendTo(b)),f},k=function(b,d){a.ev.triggerHandler("mfp"+b,d);a.st.callbacks&&(b=b.charAt(0).toLowerCase()+
b.slice(1),a.st.callbacks[b]&&a.st.callbacks[b].apply(a,c.isArray(d)?d:[d]))},n=function(b){return b===g&&a.currTemplate.closeBtn||(a.currTemplate.closeBtn=c(a.st.closeMarkup.replace("%title%",a.st.tClose)),g=b),a.currTemplate.closeBtn},A=function(){c.magnificPopup.instance||(a=new h,a.init(),c.magnificPopup.instance=a)},G=function(){var a=document.createElement("p").style,b=["ms","O","Moz","Webkit"];if(void 0!==a.transition)return!0;for(;b.length;)if(b.pop()+"Transition"in a)return!0;return!1};h.prototype=
{constructor:h,init:function(){var d=navigator.appVersion;a.isLowIE=a.isIE8=document.all&&!document.addEventListener;a.isAndroid=/android/gi.test(d);a.isIOS=/iphone|ipad|ipod/gi.test(d);a.supportsTransition=G();a.probablyMobile=a.isAndroid||a.isIOS||/(Opera Mini)|Kindle|webOS|BlackBerry|(Opera Mobi)|(Windows Phone)|IEMobile/i.test(navigator.userAgent);b=c(document);a.popupsCache={}},open:function(d){var e;if(!1===d.isObj){a.items=d.items.toArray();a.index=0;var g,r=d.items;for(e=0;e<r.length;e++)if(g=
r[e],g.parsed&&(g=g.el[0]),g===d.el[0]){a.index=e;break}}else a.items=c.isArray(d.items)?d.items:[d.items],a.index=d.index||0;if(a.isOpen)return void a.updateItemHTML();a.types=[];f="";d.mainEl&&d.mainEl.length?a.ev=d.mainEl.eq(0):a.ev=b;d.key?(a.popupsCache[d.key]||(a.popupsCache[d.key]={}),a.currTemplate=a.popupsCache[d.key]):a.currTemplate={};a.st=c.extend(!0,{},c.magnificPopup.defaults,d);a.fixedContentPos="auto"===a.st.fixedContentPos?!a.probablyMobile:a.st.fixedContentPos;a.st.modal&&(a.st.closeOnContentClick=
!1,a.st.closeOnBgClick=!1,a.st.showCloseBtn=!1,a.st.enableEscapeKey=!1);a.bgOverlay||(a.bgOverlay=q("bg").on("click.mfp",function(){a.close()}),a.wrap=q("wrap").attr("tabindex",-1).on("click.mfp",function(b){a._checkIfClose(b.target)&&a.close()}),a.container=q("container",a.wrap));a.contentContainer=q("content");a.st.preloader&&(a.preloader=q("preloader",a.container,a.st.tLoading));g=c.magnificPopup.modules;for(e=0;e<g.length;e++)r=g[e],r=r.charAt(0).toUpperCase()+r.slice(1),a["init"+r].call(a);k("BeforeOpen");
a.st.showCloseBtn&&(a.st.closeBtnInside?(l("MarkupParse",function(a,b,c,d){c.close_replaceWith=n(d.type)}),f+=" mfp-close-btn-in"):a.wrap.append(n()));a.st.alignTop&&(f+=" mfp-align-top");a.fixedContentPos?a.wrap.css({overflow:a.st.overflowY,overflowX:"hidden",overflowY:a.st.overflowY}):a.wrap.css({top:p.scrollTop(),position:"absolute"});(!1===a.st.fixedBgPos||"auto"===a.st.fixedBgPos&&!a.fixedContentPos)&&a.bgOverlay.css({height:b.height(),position:"absolute"});a.st.enableEscapeKey&&b.on("keyup.mfp",
function(b){27===b.keyCode&&a.close()});p.on("resize.mfp",function(){a.updateSize()});a.st.closeOnContentClick||(f+=" mfp-auto-cursor");f&&a.wrap.addClass(f);e=a.wH=p.height();g={};a.fixedContentPos&&a._hasScrollBar(e)&&(r=a._getScrollbarSize())&&(g.marginRight=r);a.fixedContentPos&&(a.isIE7?c("body, html").css("overflow","hidden"):g.overflow="hidden");r=a.st.mainClass;return a.isIE7&&(r+=" mfp-ie7"),r&&a._addClassToMFP(r),a.updateItemHTML(),k("BuildControls"),c("html").css(g),a.bgOverlay.add(a.wrap).prependTo(a.st.prependTo||
c(document.body)),a._lastFocusedEl=document.activeElement,setTimeout(function(){a.content?(a._addClassToMFP("mfp-ready"),a._setFocus()):a.bgOverlay.addClass("mfp-ready");b.on("focusin.mfp",a._onFocusIn)},16),a.isOpen=!0,a.updateSize(e),k("Open"),d},close:function(){a.isOpen&&(k("BeforeClose"),a.isOpen=!1,a.st.removalDelay&&!a.isLowIE&&a.supportsTransition?(a._addClassToMFP("mfp-removing"),setTimeout(function(){a._close()},a.st.removalDelay)):a._close())},_close:function(){k("Close");var d="mfp-removing mfp-ready ";
if(a.bgOverlay.detach(),a.wrap.detach(),a.container.empty(),a.st.mainClass&&(d+=a.st.mainClass+" "),a._removeClassFromMFP(d),a.fixedContentPos)d={marginRight:""},a.isIE7?c("body, html").css("overflow",""):d.overflow="",c("html").css(d);b.off("keyup.mfp focusin.mfp");a.ev.off(".mfp");a.wrap.attr("class","mfp-wrap").removeAttr("style");a.bgOverlay.attr("class","mfp-bg");a.container.attr("class","mfp-container");!a.st.showCloseBtn||a.st.closeBtnInside&&!0!==a.currTemplate[a.currItem.type]||a.currTemplate.closeBtn&&
a.currTemplate.closeBtn.detach();a.st.autoFocusLast&&a._lastFocusedEl&&c(a._lastFocusedEl).focus();a.currItem=null;a.content=null;a.currTemplate=null;a.prevHeight=0;k("AfterClose")},updateSize:function(b){a.isIOS?(b=document.documentElement.clientWidth/window.innerWidth*window.innerHeight,a.wrap.css("height",b),a.wH=b):a.wH=b||p.height();a.fixedContentPos||a.wrap.css("height",a.wH);k("Resize")},updateItemHTML:function(){var b=a.items[a.index];a.contentContainer.detach();a.content&&a.content.detach();
b.parsed||(b=a.parseEl(a.index));var e=b.type;if(k("BeforeChange",[a.currItem?a.currItem.type:"",e]),a.currItem=b,!a.currTemplate[e]){var f=a.st[e]?a.st[e].markup:!1;k("FirstMarkupParse",f);f?a.currTemplate[e]=c(f):a.currTemplate[e]=!0}d&&d!==b.type&&a.container.removeClass("mfp-"+d+"-holder");f=a["get"+e.charAt(0).toUpperCase()+e.slice(1)](b,a.currTemplate[e]);a.appendContent(f,e);b.preloaded=!0;k("Change",b);d=b.type;a.container.prepend(a.contentContainer);k("AfterChange")},appendContent:function(b,
c){(a.content=b)?a.st.showCloseBtn&&a.st.closeBtnInside&&!0===a.currTemplate[c]?a.content.find(".mfp-close").length||a.content.append(n()):a.content=b:a.content="";k("BeforeAppend");a.container.addClass("mfp-"+c+"-holder");a.contentContainer.append(a.content)},parseEl:function(b){var d,e=a.items[b];if(e.tagName?e={el:c(e)}:(d=e.type,e={data:e,src:e.src}),e.el){for(var f=a.types,g=0;g<f.length;g++)if(e.el.hasClass("mfp-"+f[g])){d=f[g];break}e.src=e.el.attr("data-mfp-src");e.src||(e.src=e.el.attr("href"))}return e.type=
d||a.st.type||"inline",e.index=b,e.parsed=!0,a.items[b]=e,k("ElementParse",e),a.items[b]},addGroup:function(b,c){var d=function(d){d.mfpEl=this;a._openClick(d,b,c)};c||(c={});c.mainEl=b;c.items?(c.isObj=!0,b.off("click.magnificPopup").on("click.magnificPopup",d)):(c.isObj=!1,c.delegate?b.off("click.magnificPopup").on("click.magnificPopup",c.delegate,d):(c.items=b,b.off("click.magnificPopup").on("click.magnificPopup",d)))},_openClick:function(b,d,e){if((void 0!==e.midClick?e.midClick:c.magnificPopup.defaults.midClick)||
!(2===b.which||b.ctrlKey||b.metaKey||b.altKey||b.shiftKey)){var f=void 0!==e.disableOn?e.disableOn:c.magnificPopup.defaults.disableOn;if(f)if(c.isFunction(f)){if(!f.call(a))return!0}else if(p.width()<f)return!0;b.type&&(b.preventDefault(),a.isOpen&&b.stopPropagation());e.el=c(b.mfpEl);e.delegate&&(e.items=d.find(e.delegate));a.open(e)}},updateStatus:function(b,c){if(a.preloader){e!==b&&a.container.removeClass("mfp-s-"+e);c||"loading"!==b||(c=a.st.tLoading);var d={status:b,text:c};k("UpdateStatus",
d);b=d.status;c=d.text;a.preloader.html(c);a.preloader.find("a").on("click",function(a){a.stopImmediatePropagation()});a.container.addClass("mfp-s-"+b);e=b}},_checkIfClose:function(b){if(!c(b).hasClass("mfp-prevent-close")){var d=a.st.closeOnContentClick,e=a.st.closeOnBgClick;if(d&&e||!a.content||c(b).hasClass("mfp-close")||a.preloader&&b===a.preloader[0])return!0;if(b===a.content[0]||c.contains(a.content[0],b)){if(d)return!0}else if(e&&c.contains(document,b))return!0;return!1}},_addClassToMFP:function(b){a.bgOverlay.addClass(b);
a.wrap.addClass(b)},_removeClassFromMFP:function(b){this.bgOverlay.removeClass(b);a.wrap.removeClass(b)},_hasScrollBar:function(c){return(a.isIE7?b.height():document.body.scrollHeight)>(c||p.height())},_setFocus:function(){(a.st.focus?a.content.find(a.st.focus).eq(0):a.wrap).focus()},_onFocusIn:function(b){return b.target===a.wrap[0]||c.contains(a.wrap[0],b.target)?void 0:(a._setFocus(),!1)},_parseMarkup:function(a,b,d){var e;d.data&&(b=c.extend(d.data,b));k("MarkupParse",[a,b,d]);c.each(b,function(b,
d){if(void 0===d||!1===d)return!0;if(e=b.split("_"),1<e.length){var f=a.find(".mfp-"+e[0]);if(0<f.length){var g=e[1];"replaceWith"===g?f[0]!==d[0]&&f.replaceWith(d):"img"===g?f.is("img")?f.attr("src",d):f.replaceWith(c("<img>").attr("src",d).attr("class",f.attr("class"))):f.attr(e[1],d)}}else a.find(".mfp-"+b).html(d)})},_getScrollbarSize:function(){if(void 0===a.scrollbarSize){var b=document.createElement("div");b.style.cssText="width: 99px; height: 99px; overflow: scroll; position: absolute; top: -9999px;";
document.body.appendChild(b);a.scrollbarSize=b.offsetWidth-b.clientWidth;document.body.removeChild(b)}return a.scrollbarSize}};c.magnificPopup={instance:null,proto:h.prototype,modules:[],open:function(a,b){return A(),a=a?c.extend(!0,{},a):{},a.isObj=!0,a.index=b||0,this.instance.open(a)},close:function(){return c.magnificPopup.instance&&c.magnificPopup.instance.close()},registerModule:function(a,b){b.options&&(c.magnificPopup.defaults[a]=b.options);c.extend(this.proto,b.proto);this.modules.push(a)},
defaults:{disableOn:0,key:null,midClick:!1,mainClass:"",preloader:!0,focus:"",closeOnContentClick:!1,closeOnBgClick:!0,closeBtnInside:!0,showCloseBtn:!0,enableEscapeKey:!0,modal:!1,alignTop:!1,removalDelay:0,prependTo:null,fixedContentPos:"auto",fixedBgPos:"auto",overflowY:"auto",closeMarkup:'<button title="%title%" type="button" class="mfp-close">&#215;</button>',tClose:"Close (Esc)",tLoading:"Loading...",autoFocusLast:!0}};c.fn.magnificPopup=function(b){A();var d=c(this);if("string"==typeof b)if("open"===
b){var e,f=m?d.data("magnificPopup"):d[0].magnificPopup,g=parseInt(arguments[1],10)||0;f.items?e=f.items[g]:(e=d,f.delegate&&(e=e.find(f.delegate)),e=e.eq(g));a._openClick({mfpEl:e},d,f)}else a.isOpen&&a[b].apply(a,Array.prototype.slice.call(arguments,1));else b=c.extend(!0,{},b),m?d.data("magnificPopup",b):d[0].magnificPopup=b,a.addGroup(d,b);return d};var x,y,u,t=function(){u&&(y.after(u.addClass(x)).detach(),u=null)};c.magnificPopup.registerModule("inline",{options:{hiddenClass:"hide",markup:"",
tNotFound:"Content not found"},proto:{initInline:function(){a.types.push("inline");l("Close.inline",function(){t()})},getInline:function(b,d){if(t(),b.src){var e=a.st.inline,f=c(b.src);if(f.length){var g=f[0].parentNode;g&&g.tagName&&(y||(x=e.hiddenClass,y=q(x),x="mfp-"+x),u=f.after(y).detach().removeClass(x));a.updateStatus("ready")}else a.updateStatus("error",e.tNotFound),f=c("<div>");return b.inlineElement=f,f}return a.updateStatus("ready"),a._parseMarkup(d,{},b),d}}});var B,w=function(){B&&c(document.body).removeClass(B)},
z=function(){w();a.req&&a.req.abort()};c.magnificPopup.registerModule("ajax",{options:{settings:null,cursor:"mfp-ajax-cur",tError:'<a href="%url%">The content</a> could not be loaded.'},proto:{initAjax:function(){a.types.push("ajax");B=a.st.ajax.cursor;l("Close.ajax",z);l("BeforeChange.ajax",z)},getAjax:function(b){B&&c(document.body).addClass(B);a.updateStatus("loading");var d=c.extend({url:b.src,success:function(d,e,f){d={data:d,xhr:f};k("ParseAjax",d);a.appendContent(c(d.data),"ajax");b.finished=
!0;w();a._setFocus();setTimeout(function(){a.wrap.addClass("mfp-ready")},16);a.updateStatus("ready");k("AjaxContentAdded")},error:function(){w();b.finished=b.loadError=!0;a.updateStatus("error",a.st.ajax.tError.replace("%url%",b.src))}},a.st.ajax.settings);return a.req=c.ajax(d),""}}});var v,H=function(b){if(b.data&&void 0!==b.data.title)return b.data.title;var d=a.st.image.titleSrc;if(d){if(c.isFunction(d))return d.call(a,b);if(b.el)return b.el.attr(d)||""}return""};c.magnificPopup.registerModule("image",
{options:{markup:'<div class="mfp-figure"><div class="mfp-close"></div><figure><div class="mfp-img"></div><figcaption><div class="mfp-bottom-bar"><div class="mfp-title"></div><div class="mfp-counter"></div></div></figcaption></figure></div>',cursor:"mfp-zoom-out-cur",titleSrc:"title",verticalFit:!0,tError:'<a href="%url%">The image</a> could not be loaded.'},proto:{initImage:function(){var b=a.st.image;a.types.push("image");l("Open.image",function(){"image"===a.currItem.type&&b.cursor&&c(document.body).addClass(b.cursor)});
l("Close.image",function(){b.cursor&&c(document.body).removeClass(b.cursor);p.off("resize.mfp")});l("Resize.image",a.resizeImage);a.isLowIE&&l("AfterChange",a.resizeImage)},resizeImage:function(){var b=a.currItem;if(b&&b.img&&a.st.image.verticalFit){var c=0;a.isLowIE&&(c=parseInt(b.img.css("padding-top"),10)+parseInt(b.img.css("padding-bottom"),10));b.img.css("max-height",a.wH-c)}},_onImageHasSize:function(b){b.img&&(b.hasSize=!0,v&&clearInterval(v),b.isCheckingImgSize=!1,k("ImageHasSize",b),b.imgHidden&&
(a.content&&a.content.removeClass("mfp-loading"),b.imgHidden=!1))},findImageSize:function(b){var c=0,d=b.img[0],e=function(f){v&&clearInterval(v);v=setInterval(function(){return 0<d.naturalWidth?void a._onImageHasSize(b):(200<c&&clearInterval(v),c++,void(3===c?e(10):40===c?e(50):100===c&&e(500)))},f)};e(1)},getImage:function(b,d){var e=0,f=function(){b&&(b.img[0].complete?(b.img.off(".mfploader"),b===a.currItem&&(a._onImageHasSize(b),a.updateStatus("ready")),b.hasSize=!0,b.loaded=!0,k("ImageLoadComplete")):
(e++,200>e?setTimeout(f,100):g()))},g=function(){b&&(b.img.off(".mfploader"),b===a.currItem&&(a._onImageHasSize(b),a.updateStatus("error",h.tError.replace("%url%",b.src))),b.hasSize=!0,b.loaded=!0,b.loadError=!0)},h=a.st.image,m=d.find(".mfp-img");if(m.length){var l=document.createElement("img");l.className="mfp-img";b.el&&b.el.find("img").length&&(l.alt=b.el.find("img").attr("alt"));b.img=c(l).on("load.mfploader",f).on("error.mfploader",g);l.src=b.src;m.is("img")&&(b.img=b.img.clone());l=b.img[0];
0<l.naturalWidth?b.hasSize=!0:l.width||(b.hasSize=!1)}return a._parseMarkup(d,{title:H(b),img_replaceWith:b.img},b),a.resizeImage(),b.hasSize?(v&&clearInterval(v),b.loadError?(d.addClass("mfp-loading"),a.updateStatus("error",h.tError.replace("%url%",b.src))):(d.removeClass("mfp-loading"),a.updateStatus("ready")),d):(a.updateStatus("loading"),b.loading=!0,b.hasSize||(b.imgHidden=!0,d.addClass("mfp-loading"),a.findImageSize(b)),d)}}});var C;c.magnificPopup.registerModule("zoom",{options:{enabled:!1,
easing:"ease-in-out",duration:300,opener:function(a){return a.is("img")?a:a.find("img")}},proto:{initZoom:function(){var b,c=a.st.zoom;if(c.enabled&&a.supportsTransition){var d,e,f=c.duration,g=function(a){a=a.clone().removeAttr("style").removeAttr("class").addClass("mfp-animated-image");var b={position:"fixed",zIndex:9999,left:0,top:0,"-webkit-backface-visibility":"hidden"};return b["-webkit-transition"]=b["-moz-transition"]=b["-o-transition"]=b.transition="all "+c.duration/1E3+"s "+c.easing,a.css(b),
a},h=function(){a.content.css("visibility","visible")};l("BuildControls.zoom",function(){if(a._allowZoom()){if(clearTimeout(d),a.content.css("visibility","hidden"),b=a._getItemToZoom(),!b)return void h();e=g(b);e.css(a._getOffset());a.wrap.append(e);d=setTimeout(function(){e.css(a._getOffset(!0));d=setTimeout(function(){h();setTimeout(function(){e.remove();b=e=null;k("ZoomAnimationEnded")},16)},f)},16)}});l("BeforeClose.zoom",function(){if(a._allowZoom()){if(clearTimeout(d),a.st.removalDelay=f,!b){if(b=
a._getItemToZoom(),!b)return;e=g(b)}e.css(a._getOffset(!0));a.wrap.append(e);a.content.css("visibility","hidden");setTimeout(function(){e.css(a._getOffset())},16)}});l("Close.zoom",function(){a._allowZoom()&&(h(),e&&e.remove(),b=null)})}},_allowZoom:function(){return"image"===a.currItem.type},_getItemToZoom:function(){return a.currItem.hasSize?a.currItem.img:!1},_getOffset:function(b){var d;d=b?a.currItem.img:a.st.zoom.opener(a.currItem.el||a.currItem);b=d.offset();var e=parseInt(d.css("padding-top"),
10),f=parseInt(d.css("padding-bottom"),10);b.top-=c(window).scrollTop()-e;d={width:d.width(),height:(m?d.innerHeight():d[0].offsetHeight)-f-e};return(void 0===C&&(C=void 0!==document.createElement("p").style.MozTransform),C)?d["-moz-transform"]=d.transform="translate("+b.left+"px,"+b.top+"px)":(d.left=b.left,d.top=b.top),d}}});var D=function(b){if(a.currTemplate.iframe){var c=a.currTemplate.iframe.find("iframe");c.length&&(b||(c[0].src="//about:blank"),a.isIE8&&c.css("display",b?"block":"none"))}};
c.magnificPopup.registerModule("iframe",{options:{markup:'<div class="mfp-iframe-scaler"><div class="mfp-close"></div><iframe class="mfp-iframe" src="//about:blank" frameborder="0" allowfullscreen></iframe></div>',srcAction:"iframe_src",patterns:{youtube:{index:"youtube.com",id:"v=",src:"//www.youtube.com/embed/%id%?autoplay=1"},vimeo:{index:"vimeo.com/",id:"/",src:"//player.vimeo.com/video/%id%?autoplay=1"},gmaps:{index:"//maps.google.",src:"%id%&output=embed"}}},proto:{initIframe:function(){a.types.push("iframe");
l("BeforeChange",function(a,b,c){b!==c&&("iframe"===b?D():"iframe"===c&&D(!0))});l("Close.iframe",function(){D()})},getIframe:function(b,d){var e=b.src,f=a.st.iframe;c.each(f.patterns,function(){return-1<e.indexOf(this.index)?(this.id&&(e="string"==typeof this.id?e.substr(e.lastIndexOf(this.id)+this.id.length,e.length):this.id.call(this,e)),e=this.src.replace("%id%",e),!1):void 0});var g={};return f.srcAction&&(g[f.srcAction]=e),a._parseMarkup(d,g,b),a.updateStatus("ready"),d}}});var E=function(b){var c=
a.items.length;return b>c-1?b-c:0>b?c+b:b},F=function(a,b,c){return a.replace(/%curr%/gi,b+1).replace(/%total%/gi,c)};c.magnificPopup.registerModule("gallery",{options:{enabled:!1,arrowMarkup:'<button title="%title%" type="button" class="mfp-arrow mfp-arrow-%dir%"></button>',preload:[0,2],navigateByImgClick:!0,arrows:!0,tPrev:"Previous (Left arrow key)",tNext:"Next (Right arrow key)",tCounter:"%curr% of %total%"},proto:{initGallery:function(){var d=a.st.gallery;return a.direction=!0,d&&d.enabled?
(f+=" mfp-gallery",l("Open.mfp-gallery",function(){d.navigateByImgClick&&a.wrap.on("click.mfp-gallery",".mfp-img",function(){return 1<a.items.length?(a.next(),!1):void 0});b.on("keydown.mfp-gallery",function(b){37===b.keyCode?a.prev():39===b.keyCode&&a.next()})}),l("UpdateStatus.mfp-gallery",function(b,c){c.text&&(c.text=F(c.text,a.currItem.index,a.items.length))}),l("MarkupParse.mfp-gallery",function(b,c,e,f){b=a.items.length;e.counter=1<b?F(d.tCounter,f.index,b):""}),l("BuildControls.mfp-gallery",
function(){if(1<a.items.length&&d.arrows&&!a.arrowLeft){var b=d.arrowMarkup,e=a.arrowLeft=c(b.replace(/%title%/gi,d.tPrev).replace(/%dir%/gi,"left")).addClass("mfp-prevent-close"),b=a.arrowRight=c(b.replace(/%title%/gi,d.tNext).replace(/%dir%/gi,"right")).addClass("mfp-prevent-close");e.click(function(){a.prev()});b.click(function(){a.next()});a.container.append(e.add(b))}}),l("Change.mfp-gallery",function(){a._preloadTimeout&&clearTimeout(a._preloadTimeout);a._preloadTimeout=setTimeout(function(){a.preloadNearbyImages();
a._preloadTimeout=null},16)}),void l("Close.mfp-gallery",function(){b.off(".mfp-gallery");a.wrap.off("click.mfp-gallery");a.arrowRight=a.arrowLeft=null})):!1},next:function(){a.direction=!0;a.index=E(a.index+1);a.updateItemHTML()},prev:function(){a.direction=!1;a.index=E(a.index-1);a.updateItemHTML()},goTo:function(b){a.direction=b>=a.index;a.index=b;a.updateItemHTML()},preloadNearbyImages:function(){var b;b=a.st.gallery.preload;var c=Math.min(b[0],a.items.length),d=Math.min(b[1],a.items.length);
for(b=1;b<=(a.direction?d:c);b++)a._preloadItem(a.index+b);for(b=1;b<=(a.direction?c:d);b++)a._preloadItem(a.index-b)},_preloadItem:function(b){if(b=E(b),!a.items[b].preloaded){var d=a.items[b];d.parsed||(d=a.parseEl(b));k("LazyLoad",d);"image"===d.type&&(d.img=c('<img class="mfp-img" />').on("load.mfploader",function(){d.hasSize=!0}).on("error.mfploader",function(){d.hasSize=!0;d.loadError=!0;k("LazyLoadError",d)}).attr("src",d.src));d.preloaded=!0}}}});c.magnificPopup.registerModule("retina",{options:{replaceSrc:function(a){return a.src.replace(/\.\w+$/,
function(a){return"@2x"+a})},ratio:1},proto:{initRetina:function(){if(1<window.devicePixelRatio){var b=a.st.retina,c=b.ratio,c=isNaN(c)?c():c;1<c&&(l("ImageHasSize.retina",function(a,b){b.img.css({"max-width":b.img[0].naturalWidth/c,width:"100%"})}),l("ElementParse.retina",function(a,d){d.src=b.replaceSrc(d,c)}))}}}});A()});
